---
title: "Using_rayyanR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using_rayyanR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rayyanR)
library(synthesisr)
library(plyr)
```

```{r}
#read in a rayyan exported bibliography file (example here is the Tinea Update one from Rayyan)
rayyan_biblio<-synthesisr::read_ref('https://raw.githubusercontent.com/befriendabacterium/rayyanR/main/example_inputs/tinea_update.ris')

```

```{r}
#parse rayyan biblio
rayyan_biblio_cleaned<-parse_rayyan(rayyan_df = rayyan_biblio)

```

```{r}
#print the outputs AND CHECK THEM AGAINST YOUR RAYYAN BIBLIOGRAPHY TO VALIDATE. The total number of records should remain the same and Inclusions and exclusions should equate straightforwardly. However, Maybes here (unlike in Rayyan) are only Maybes by if all reviewers marked them as so, and Conflicts include Maybe-Inclusion/Exclusion type conflicts (in Rayyan a 'conflict' is only an Inclusion-Exclusion type conflict).

summary_df<-plyr::count(rayyan_biblio_cleaned$finaldecision)
colnames(summary_df)<-c('decision','records_n')
print(summary_df)
```


